name: Rust

on:
  push:
    branches: [ "release/**" ]
    paths:
      - Cargo.toml
  
jobs:

  lib_build_all:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@release/**
      - name: lib_build_all
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --release --target  --target=i686-pc-windows-msvc
