name: Rust

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Cargo.toml 
  
jobs:

  lib_build_all:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: lib_build_all
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --release --target  --target=i686-pc-windows-msvc
